# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Zhilong Chen
title: Heterogeneous Computation Engineer
email: firstname.lastname@mail.mcgill.ca
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  Bye-legume
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's zhilong and I'm a software engineer at Huawei Canada. Hyper-Contributer to [Ray](https://github.com/ray-project/ray). A highly skilled High-Performance Computing Engineer with extensive experience in distributed computing frameworks like RAY and SPARK, and a proven track record in federated learning and large model development. Adept at optimizing machine learning models and processes, with a strong background in mathematical modeling and cryptographic computing technologies. Holds multiple patents in data processing and machine learning methodologies. Known for enhancing system efficiencies and adept at identifying and resolving performance bottlenecks.
  
  I am most skilled in: Ray,Pyhton, C++, kubernetes and Cooking.

content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
#        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
#          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#          #   icon: fab fa-github
#          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Huawei Canada
        link: https://www.huawei.com/ca/
        # link_text: boringcompany.com
        sub_title: Heterogeneous Computation Engineer
        caption: June 2023 - Present
        quote: >
          Lower the barrier for using heterogeneous GPU clusters, allowing everyone to enjoy the fun of AI.
        description: | # this will include new lines to allow paragraphs
            - Contributed to the Anyscale Ray project, improving task dispatching order for higher NPU usage. Have contributed more than 20 commits to Ray project.
            - Optimized task scheduling for the RAY distributed computing framework to reduce communication overhead and improve computational efficiency.
            - Using tools like Grafana, Loki, Prometheus, etc., to enhance the visualization capabilities of RAY, enabling engineers to more easily identify performance bottlenecks and carry out targeted optimizations.
            - Optimized the deployment strategy for LLM servers, enhancing the processing capabilities of the RAY SERVER components and significantly improving the ability to handle user requests for multimodal models.
            - Optimized the RAY DATA library from the bottom to the top layer, resulting in a reduction of more than 50% in random query end-to-end time.
            
  - layout: left
        title: Huakongqingjiao Inc.
        sub_title: Federated Learning Architect
        caption: Nov 2022 - Jan 2023
        description: |
          - Developed LLM algorithms based on federated learning, including deployment and subsequent release.
          - Led the design and product planning of an open-source federated learning architecture, covering aspects like control flow, data flow, load balancing, and communication control.
          - Refactored federated learning code to improve usability and reduce learning costs for users and clients.

      - layout: left
        title: Huakongqingjiao Inc.
        sub_title: Software Developer
        caption: Nov 2020 - Nov 2022
        description: |
          - Built federated learning frameworks from scratch using various algorithms such as Logistic Regression, XGBoost, and Linear Regression, focusing on secure multi-party computation and homomorphic encryption.
          - Developed algorithm libraries based on MPC, including privacy-numpy and a scorecard library.
          - Enabled privacy-preserved XGBoost to handle large-scale datasets (over 200 million samples), reducing runtime from 4 hours to 50 minutes.
          - Led a project for big data collaboration across MPC platforms, achieving high performance and compliance with data protection regulations.

  
  - title: Education
    layout: list
    content:
      - layout: left
        title: McGill University
        caption: Jan 2018 - Apr 2020
        sub_title: MSc Computer Science
        quote: >
          "There are two magic tricks in Math: adding zero and multiplying by one."
        description: |
          During my time at McGill University, I took courses such as Applied Machine Learning, Optimization, and Fundamentals of Computer Vision. My education gave me a strong foundation in both theoretical and applied computer science, and I was also a Teaching Assistant for key courses like Applied Machine Learning and Numerical Computing.

      - layout: left
        title: Nanjing University of Aeronautics and Astronautics
        caption: Sep 2012 - Jun 2016
        sub_title: BSc Computer Science
        description: |
          Courses included Programming Language, Discrete Mathematics, Mathematical Analysis, and Numerical Linear Algebra. Awarded scholarships for all four years of undergraduate study.

  - title: Patents
    layout: list
    content:
      - layout: left
        title: Selected Patents
        description: |
          - 2022116717485: A Method, Apparatus, and Electronic Device for Encrypted Data Fitting Computation.
          - 2022112296044: A Weight Aggregation Method, Apparatus, and System in Model Training.
          - 2022112946574: A Method, Apparatus, and Electronic Device for Encrypted Data Computation.
          - 202210645371X: A Model Training Method and Secure Multi-Party Computation System.

  - title: A Little More About Me
    layout: text
    content: |
      Beyond my professional pursuits in high-performance computing and federated learning, I enjoy:
      - Gaming
      - Cooking
      - French


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
